# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare Jaguar2
      uses: actions/checkout@v3
      with:
        repository: ericksonlbs/jaguar2        
        path: jaguar2-repo # diretório onde o repositório será clonado
    - name: Compile dependency
      run: |
        cd jaguar2-repo
        ./mvnw install -pl !jaguar2-validations
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: jaguar
        path: target/jaguar2.xml
        retention-days: 5
